#!/usr/bin/env bash
# build-deb.sh — produce enforcer-mcp_<version>_all.deb
#
# Why hand-rolled instead of `dpkg-buildpackage` / `debhelper`?
#   1. Our payload is just static Python files + a venv built on the target
#      via postinst. There's no compile step to orchestrate, no native
#      bindings to cross-compile, nothing dh_* needs to "help" with.
#   2. Operators of a swarm node may not have a Debian dev toolchain
#      installed. `dpkg-deb` alone is in every dpkg system. This script
#      runs in a Docker container or even directly on the target.
#   3. We get a 5-line script that's auditable end-to-end vs a debian/
#      tree full of magic Makefile variables.
#
# Usage:
#   ./packaging/build-deb.sh                  # builds into ./dist/
#   ./packaging/build-deb.sh --version 0.2.0  # override version
#
# Output: ./dist/enforcer-mcp_<version>_all.deb

set -euo pipefail

# ── Locate ourselves so the script works from any CWD ─────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$PROJECT_DIR/dist"
PKG_NAME="enforcer-mcp"

# ── Parse args ────────────────────────────────────────────────────────
VERSION=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        --help|-h)
            sed -n '2,/^set/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

# Pull version from the changelog if not overridden — single source of truth.
if [[ -z "$VERSION" ]]; then
    CHANGELOG="$SCRIPT_DIR/debian/changelog"
    VERSION=$(head -1 "$CHANGELOG" | sed -E 's/.*\(([^)]+)\).*/\1/')
fi
echo "→ building $PKG_NAME $VERSION (arch: all)"

# ── Sanity checks ─────────────────────────────────────────────────────
command -v dpkg-deb >/dev/null \
    || { echo "dpkg-deb not found. apt install dpkg-dev"; exit 1; }
[[ -f "$PROJECT_DIR/server.py" ]] \
    || { echo "server.py missing — run from project root"; exit 1; }
[[ -f "$PROJECT_DIR/requirements.txt" ]] \
    || { echo "requirements.txt missing"; exit 1; }

# ── Build staging tree ────────────────────────────────────────────────
STAGE=$(mktemp -d -t enforcer-mcp-build.XXXXXX)
trap 'rm -rf "$STAGE"' EXIT
echo "  staging in $STAGE"

# DEBIAN/ — control files
install -d -m 0755 "$STAGE/DEBIAN"
install -m 0644 "$SCRIPT_DIR/debian/control"   "$STAGE/DEBIAN/control"
install -m 0644 "$SCRIPT_DIR/debian/copyright" "$STAGE/DEBIAN/copyright"
# NOTE: we deliberately don't ship a conffiles file. /etc/enforcer-mcp/
# config.yaml is generated by postinst (with a fresh bearer token) on
# first install and the postinst guards against overwriting on upgrade.
# `conffiles` would require the file to be in the .deb itself, which
# would mean shipping a placeholder token — gross.
install -m 0755 "$SCRIPT_DIR/debian/postinst"  "$STAGE/DEBIAN/postinst"
install -m 0755 "$SCRIPT_DIR/debian/prerm"     "$STAGE/DEBIAN/prerm"
install -m 0755 "$SCRIPT_DIR/debian/postrm"    "$STAGE/DEBIAN/postrm"

# Pin the version from the changelog into the control file. dpkg-deb is
# happy as long as Version: appears anywhere in the binary control stanza;
# inserting after the Package: header keeps it scannable for humans too.
sed -i '/^Package:/a Version: '"$VERSION" "$STAGE/DEBIAN/control"

# /opt/enforcer-mcp/ — application files. Stay strictly in step with what
# the cockpit + chroot quickstart already expect.
install -d -m 0755 "$STAGE/opt/enforcer-mcp"
install -m 0644 "$PROJECT_DIR/server.py"           "$STAGE/opt/enforcer-mcp/"
install -m 0644 "$PROJECT_DIR/requirements.txt"    "$STAGE/opt/enforcer-mcp/"
install -m 0644 "$PROJECT_DIR/README.md"           "$STAGE/opt/enforcer-mcp/"
install -m 0644 "$PROJECT_DIR/config.yaml.example" "$STAGE/opt/enforcer-mcp/"

# handlers/ — Python package (top-level *.py only; self-contained CLI tools
# like the GTFOBins lookup now live in scripts/ alongside wpasec-upload).
install -d -m 0755 "$STAGE/opt/enforcer-mcp/handlers"
for f in "$PROJECT_DIR/handlers/"*.py; do
    [[ -f "$f" ]] || continue
    install -m 0644 "$f" "$STAGE/opt/enforcer-mcp/handlers/"
done

# data/ — bundled databases shipped read-only (e.g. gtfobins_cache.json, the
# 478-binary GTFOBins DB). scripts/gtfobins-mcp resolves this path first.
if [[ -d "$PROJECT_DIR/data" ]]; then
    install -d -m 0755 "$STAGE/opt/enforcer-mcp/data"
    for f in "$PROJECT_DIR/data/"*; do
        [[ -f "$f" ]] || continue
        install -m 0644 "$f" "$STAGE/opt/enforcer-mcp/data/"
    done
fi

# scripts/ — wpa-sec helpers. install -m 0755 because postinst symlinks
# these into /usr/bin (or operators can do it manually).
install -d -m 0755 "$STAGE/opt/enforcer-mcp/scripts"
for f in "$PROJECT_DIR/scripts/"*; do
    [[ -f "$f" ]] || continue
    install -m 0755 "$f" "$STAGE/opt/enforcer-mcp/scripts/"
done
# Also symlink them into /usr/bin so they're in $PATH without postinst
# manually managing it. dpkg handles symlink ownership cleanly.
install -d -m 0755 "$STAGE/usr/bin"
for f in "$PROJECT_DIR/scripts/"*; do
    [[ -f "$f" ]] || continue
    name=$(basename "$f")
    ln -sf "/opt/enforcer-mcp/scripts/$name" "$STAGE/usr/bin/$name"
done

# systemd unit
install -d -m 0755 "$STAGE/lib/systemd/system"
install -m 0644 "$SCRIPT_DIR/systemd/enforcer-mcp.service" \
                "$STAGE/lib/systemd/system/enforcer-mcp.service"

# SysV init script — for non-systemd nodes (Kali chroot, minimal images).
# postinst registers it (update-rc.d) + installs a cron watchdog ONLY when
# real systemd is absent; on systemd hosts it sits inert and unused.
install -d -m 0755 "$STAGE/etc/init.d"
install -m 0755 "$SCRIPT_DIR/initd/enforcer-mcp" \
                "$STAGE/etc/init.d/enforcer-mcp"

# Empty /etc/enforcer-mcp/ — postinst populates it on first install,
# `conffiles` protects it on upgrade. Creating the dir here so dpkg owns it.
install -d -m 0755 "$STAGE/etc/enforcer-mcp"

# ── md5sums ───────────────────────────────────────────────────────────
# Optional but every nice .deb has them. dpkg uses them on `--verify`.
(
    cd "$STAGE"
    find . -path ./DEBIAN -prune -o -type f -print | \
        sed 's|^\./||' | \
        xargs md5sum > DEBIAN/md5sums 2>/dev/null || true
)
chmod 0644 "$STAGE/DEBIAN/md5sums"

# ── Build ─────────────────────────────────────────────────────────────
mkdir -p "$DIST_DIR"
OUT="$DIST_DIR/${PKG_NAME}_${VERSION}_all.deb"
dpkg-deb --root-owner-group --build "$STAGE" "$OUT"

# ── Report ────────────────────────────────────────────────────────────
echo
echo "✓ built $OUT"
echo "  size: $(du -h "$OUT" | cut -f1)"
echo
echo "Inspect with:"
echo "  dpkg-deb --info     $OUT"
echo "  dpkg-deb --contents $OUT"
echo
echo "Install on a node with:"
echo "  scp $OUT node:/tmp/"
echo "  ssh node 'sudo apt install /tmp/$(basename "$OUT")'"
echo
echo "The bearer token is generated on first install and printed in the"
echo "postinst output AND saved to /etc/enforcer-mcp/config.yaml."

# ─── Auto-sync into the frontend APK asset dir ───────────────────────
# The cockpit's [Deploy New Node] flow ships the bundled .deb over
# Tailscale to targets. If the asset here goes stale relative to the
# freshly-built .deb, the next EAS build will still ship the old bytes.
# We copy the .deb + regenerate the sidecar sha256 so that pain goes
# away — the operator only needs to remember `build-deb.sh`.
#
# We look for the frontend directory relative to this script; if the
# repo isn't laid out the usual way (e.g. building from a tarball),
# we skip silently.
_FRONTEND_ASSETS="$(cd "$(dirname "$0")/../../frontend/assets/enforcer-node" 2>/dev/null && pwd || true)"
if [[ -n "$_FRONTEND_ASSETS" && -d "$_FRONTEND_ASSETS" ]]; then
    cp -f "$OUT" "$_FRONTEND_ASSETS/enforcer-mcp.deb"
    sha256sum "$_FRONTEND_ASSETS/enforcer-mcp.deb" | awk '{print $1}' \
        > "$_FRONTEND_ASSETS/enforcer-mcp.deb.sha256"
    echo
    echo "→ synced into frontend APK asset dir: $_FRONTEND_ASSETS"
    echo "  Next EAS build will bundle $VERSION."
fi
