/**
 * Expo config plugin that DEFINITIVELY enables cleartext HTTP for the
 * cockpit's local-loopback + Tailscale-mesh traffic.
 *
 * Why a custom plugin instead of relying on `expo.android.usesCleartextTraffic`?
 *
 *   1. Some Expo SDK versions silently drop the JSON-level flag.
 *   2. React Native's bundled release-mode network_security_config.xml
 *      is restrictive and OVERRIDES the manifest-level usesCleartextTraffic
 *      flag — `android:networkSecurityConfig` wins over the bare attribute.
 *   3. We want explicit allowlisting: cleartext OK for 127.0.0.1 + Tailscale
 *      CGNAT (100.64/10) ranges + any custom host we want, NOT for the
 *      whole world.
 *
 * What this plugin does at prebuild time:
 *   A. Writes android/app/src/main/res/xml/enforcer_net_config.xml with a
 *      base-config that ALLOWS cleartext for our specific domains.
 *   B. Sets application[android:networkSecurityConfig]="@xml/enforcer_net_config"
 *      so React Native's restrictive default doesn't apply.
 *   C. Also sets application[android:usesCleartextTraffic]="true" as a
 *      belt-and-suspenders safety net.
 */
const { withDangerousMod, withAndroidManifest } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const NET_CONFIG_FILENAME = "enforcer_net_config.xml";

// Network Security Config — Android 9+ schema.
// Cleartext is permitted ONLY for the listed domains. Everything else
// remains HTTPS-enforced (this is what the system-default would be).
//
// 127.0.0.1 / localhost — chroot MCP server loopback
// 10.0.0.0/8           — typical home LAN (also catches Magisk's mock interface)
// 192.168.0.0/16       — typical home LAN
// 100.64.0.0/10        — Tailscale CGNAT range (all tailnet IPs land here)
//
// `includeSubdomains="true"` doesn't apply to IPs; it's harmless for them.
const NET_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by withCleartextTraffic Expo config plugin.
  DO NOT EDIT MANUALLY — changes will be overwritten on next prebuild.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="true">10.0.0.0</domain>
        <domain includeSubdomains="true">192.168.0.0</domain>
        <!-- Tailscale CGNAT range — covers all 100.64.0.0/10 nodes -->
        <domain includeSubdomains="true">100.64.0.0</domain>
        <domain includeSubdomains="true">100.65.0.0</domain>
        <domain includeSubdomains="true">100.66.0.0</domain>
        <domain includeSubdomains="true">100.67.0.0</domain>
        <domain includeSubdomains="true">100.68.0.0</domain>
        <domain includeSubdomains="true">100.69.0.0</domain>
        <domain includeSubdomains="true">100.70.0.0</domain>
        <domain includeSubdomains="true">100.71.0.0</domain>
        <domain includeSubdomains="true">100.72.0.0</domain>
        <domain includeSubdomains="true">100.73.0.0</domain>
        <domain includeSubdomains="true">100.74.0.0</domain>
        <domain includeSubdomains="true">100.75.0.0</domain>
        <domain includeSubdomains="true">100.76.0.0</domain>
        <domain includeSubdomains="true">100.77.0.0</domain>
        <domain includeSubdomains="true">100.78.0.0</domain>
        <domain includeSubdomains="true">100.79.0.0</domain>
        <domain includeSubdomains="true">100.80.0.0</domain>
        <domain includeSubdomains="true">100.81.0.0</domain>
        <domain includeSubdomains="true">100.82.0.0</domain>
        <domain includeSubdomains="true">100.83.0.0</domain>
        <domain includeSubdomains="true">100.84.0.0</domain>
        <domain includeSubdomains="true">100.85.0.0</domain>
        <domain includeSubdomains="true">100.86.0.0</domain>
        <domain includeSubdomains="true">100.87.0.0</domain>
        <domain includeSubdomains="true">100.88.0.0</domain>
        <domain includeSubdomains="true">100.89.0.0</domain>
        <domain includeSubdomains="true">100.90.0.0</domain>
        <domain includeSubdomains="true">100.91.0.0</domain>
        <domain includeSubdomains="true">100.92.0.0</domain>
        <domain includeSubdomains="true">100.93.0.0</domain>
        <domain includeSubdomains="true">100.94.0.0</domain>
        <domain includeSubdomains="true">100.95.0.0</domain>
        <domain includeSubdomains="true">100.96.0.0</domain>
        <domain includeSubdomains="true">100.97.0.0</domain>
        <domain includeSubdomains="true">100.98.0.0</domain>
        <domain includeSubdomains="true">100.99.0.0</domain>
        <domain includeSubdomains="true">100.100.0.0</domain>
        <domain includeSubdomains="true">100.101.0.0</domain>
        <domain includeSubdomains="true">100.102.0.0</domain>
        <domain includeSubdomains="true">100.103.0.0</domain>
        <domain includeSubdomains="true">100.104.0.0</domain>
        <domain includeSubdomains="true">100.105.0.0</domain>
        <domain includeSubdomains="true">100.106.0.0</domain>
        <domain includeSubdomains="true">100.107.0.0</domain>
        <domain includeSubdomains="true">100.108.0.0</domain>
        <domain includeSubdomains="true">100.109.0.0</domain>
        <domain includeSubdomains="true">100.110.0.0</domain>
        <domain includeSubdomains="true">100.111.0.0</domain>
        <domain includeSubdomains="true">100.112.0.0</domain>
        <domain includeSubdomains="true">100.113.0.0</domain>
        <domain includeSubdomains="true">100.114.0.0</domain>
        <domain includeSubdomains="true">100.115.0.0</domain>
        <domain includeSubdomains="true">100.116.0.0</domain>
        <domain includeSubdomains="true">100.117.0.0</domain>
        <domain includeSubdomains="true">100.118.0.0</domain>
        <domain includeSubdomains="true">100.119.0.0</domain>
        <domain includeSubdomains="true">100.120.0.0</domain>
        <domain includeSubdomains="true">100.121.0.0</domain>
        <domain includeSubdomains="true">100.122.0.0</domain>
        <domain includeSubdomains="true">100.123.0.0</domain>
        <domain includeSubdomains="true">100.124.0.0</domain>
        <domain includeSubdomains="true">100.125.0.0</domain>
        <domain includeSubdomains="true">100.126.0.0</domain>
        <domain includeSubdomains="true">100.127.0.0</domain>
        <!-- Tailscale MagicDNS suffixes — these are .ts.net by default -->
        <domain includeSubdomains="true">ts.net</domain>
    </domain-config>
</network-security-config>
`;

function withCleartextResource(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const resXmlDir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/res/xml",
      );
      fs.mkdirSync(resXmlDir, { recursive: true });
      const dst = path.join(resXmlDir, NET_CONFIG_FILENAME);
      fs.writeFileSync(dst, NET_CONFIG_XML, "utf8");
      console.log(`[withCleartextTraffic] ✓ wrote ${dst} (${NET_CONFIG_XML.length} bytes)`);
      return config;
    },
  ]);
}

function withCleartextManifest(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;
    if (!manifest.application || !manifest.application.length) {
      console.warn("[withCleartextTraffic] ⚠ no <application> tag found — skipping");
      return config;
    }
    const app = manifest.application[0];
    app.$ = app.$ || {};
    app.$["android:networkSecurityConfig"] = `@xml/${NET_CONFIG_FILENAME.replace(/\.xml$/, "")}`;
    app.$["android:usesCleartextTraffic"] = "true";
    console.log(
      `[withCleartextTraffic] ✓ patched <application> ` +
      `(networkSecurityConfig=@xml/${NET_CONFIG_FILENAME.replace(/\.xml$/, "")}, usesCleartextTraffic=true)`,
    );
    return config;
  });
}

module.exports = function withCleartextTraffic(config) {
  console.log("[withCleartextTraffic] plugin invoked");
  config = withCleartextResource(config);
  config = withCleartextManifest(config);
  return config;
};
