/**
 * Expo config plugin that DEFINITIVELY enables cleartext HTTP for the
 * cockpit's local-loopback + Tailscale-mesh traffic.
 *
 * Why a custom plugin instead of relying on `expo.android.usesCleartextTraffic`?
 *
 *   1. Some Expo SDK versions silently drop the JSON-level flag.
 *   2. React Native's bundled release-mode network_security_config.xml
 *      is restrictive and OVERRIDES the manifest-level usesCleartextTraffic
 *      flag — `android:networkSecurityConfig` wins over the bare attribute.
 *   3. We want explicit allowlisting: cleartext OK for 127.0.0.1 + Tailscale
 *      CGNAT (100.64/10) ranges + any custom host we want, NOT for the
 *      whole world.
 *
 * What this plugin does at prebuild time:
 *   A. Writes android/app/src/main/res/xml/enforcer_net_config.xml with a
 *      base-config that ALLOWS cleartext for our specific domains.
 *   B. Sets application[android:networkSecurityConfig]="@xml/enforcer_net_config"
 *      so React Native's restrictive default doesn't apply.
 *   C. Also sets application[android:usesCleartextTraffic]="true" as a
 *      belt-and-suspenders safety net.
 */
const { withDangerousMod, withAndroidManifest } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const NET_CONFIG_FILENAME = "enforcer_net_config.xml";

// Network Security Config — Android 9+ schema.
//
// HISTORY: An earlier version tried to limit cleartext to specific IP
// ranges (loopback + Tailscale CGNAT 100.64/10 + RFC1918). That
// approach silently DOES NOT WORK because Android's <domain> matching
// for IP literals is exact-string only — there is no CIDR, no subnet,
// no `includeSubdomains` semantics for IPs. The result was that any
// Tailscale tailnet IP other than the exact `100.X.0.0` boundaries
// got rejected with "cleartext traffic not permitted" and surfaced as
// "unreachable" in the // nodes tab.
//
// CURRENT POLICY: cleartext is permitted globally. Justification:
//
//   1. The app only ever calls MCP endpoints that the operator
//      themselves provisioned (chroot loopback, tailnet nodes,
//      occasionally LAN/dev machines). Every endpoint is explicitly
//      added by hand via // nodes — there is no "drive-by" cleartext.
//   2. Threat model assumes a trusted operator-controlled network.
//      The phone is the cockpit; nodes are personally deployed via
//      our .deb. Adversarial cleartext interception requires
//      ARP-spoofing the operator's own tailnet, at which point we
//      have bigger problems than this app's transport security.
//   3. We still trust system certs for HTTPS URLs (e.g. future
//      Emergent LLM key calls), so accidental MITM of those is still
//      blocked by Android's default CA pinning.
//
// If we ever need stricter posture (multi-tenant nodes, customer
// installs etc.) the right move is to migrate to HTTPS with a local
// CA and pin in the NSC — not to play whack-a-mole with literal IP
// allowlists.
const NET_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by withCleartextTraffic Expo config plugin.
  DO NOT EDIT MANUALLY — changes will be overwritten on next prebuild.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
</network-security-config>
`;

function withCleartextResource(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const resXmlDir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/res/xml",
      );
      fs.mkdirSync(resXmlDir, { recursive: true });
      const dst = path.join(resXmlDir, NET_CONFIG_FILENAME);
      fs.writeFileSync(dst, NET_CONFIG_XML, "utf8");
      console.log(`[withCleartextTraffic] ✓ wrote ${dst} (${NET_CONFIG_XML.length} bytes)`);
      return config;
    },
  ]);
}

function withCleartextManifest(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;
    if (!manifest.application || !manifest.application.length) {
      console.warn("[withCleartextTraffic] ⚠ no <application> tag found — skipping");
      return config;
    }
    const app = manifest.application[0];
    app.$ = app.$ || {};
    app.$["android:networkSecurityConfig"] = `@xml/${NET_CONFIG_FILENAME.replace(/\.xml$/, "")}`;
    app.$["android:usesCleartextTraffic"] = "true";
    console.log(
      `[withCleartextTraffic] ✓ patched <application> ` +
      `(networkSecurityConfig=@xml/${NET_CONFIG_FILENAME.replace(/\.xml$/, "")}, usesCleartextTraffic=true)`,
    );
    return config;
  });
}

module.exports = function withCleartextTraffic(config) {
  console.log("[withCleartextTraffic] plugin invoked");
  config = withCleartextResource(config);
  config = withCleartextManifest(config);
  return config;
};
